description: Example run of model training
budget: ai2/aristo
tasks:
  - name: model_discovery_train
    image:
      beaker: 01J2B364PYAWDN9HN2R6C5TCSY
    command: [
    python, -m, model_discovery.run,
    --ckpt_dir, /output,
    --data_dir,/data,
    ]
    envVars:
      - name: HF_KEY
        secret: HF_TOKEN_SECRET
      - name: WANDB_API_KEY
        secret: WANDB_API_KEY_SECRET
    datasets:
      - mountPath: /data
        source:
          beaker: 01J2AYF57RFQAHR0C906W6KTSG
    result:
      path: /output
    resources:
      gpuCount: 1
    context:
      priority: normal
      preemptible: true
    constraints:
      cluster:
        - ai2/aristo-elanding-a6000