description: Example run of model training
budget: ai2/aristo
tasks:
  - name: model_discovery_train
    image:
      beaker: 01J2A76ESJGYCGVBHWQZ89RMW3
    command: [
    python, -m, model_discovery.run,
    --ckpt_dir, /output,
    --data_dir, /output,
    ]
    envVars:
      - name: HF_KEY
        secret: HF_TOKEN_SECRET
    result:
      path: /output
    resources:
      gpuCount: 1
    context:
      priority: low
      preemptible: true
    constraints:
      cluster:
        - ai2/aristo-elanding-a6000