version: v2
budget: ai2/aristo
description: This is an example mixing experiment configuration file.
tasks:
  - name: genesys-v-node
    image:
      beaker: junyanc/genesys-i1
    command: [genesys, node, -V]
    arguments: []
    envVars:
      - name: MY_OPENAI_KEY
        secret: MY_OPENAI_KEY 
      - name: TOGETHER_API_KEYz
        secret: TOGETHER_API_KEY
      - name: ANTHROPIC_API_KEY
        secret: ANTHROPIC_API_KEY
      - name: WANDB_API_KEY
        secret: WANDB_API_KEY
      - name: S2_API_KEY
        secret: S2_API_KEY
      - name: PINECONE_API_KEY
        secret: PINECONE_API_KEY
      - name: COHERE_API_KEY
        secret: COHERE_API_KEY
      - name: PERPLEXITY_API_KEY
        secret: PERPLEXITY_API_KEY
      - name: MATHPIX_API_ID
        secret: MATHPIX_API_ID
      - name: FIREBASE_KEY
        secret: FIREBASE_KEY
      - name: HF_KEY
        secret: HF_KEY
      - name: HF_HUB_KEY
        secret: HF_HUB_KEY
      - name: GITHUB_TOKEN
        secret: GITHUB_TOKEN
      - name: HF_DATASETS_TRUST_REMOTE_CODE
        value: 1
      - name: DATA_DIR
        value: /home/data
      - name: CKPT_DIR
        value: /home/ckpt
      - name: DB_KEY_PATH
        value: /home/secrets/db_key.json
    datasets:
      - mountPath: /home/data
        source:
          beaker: junyanc/genesys-corpus
    result:
      path: /home/ckpt
    resources:
      gpuCount: 2
      sharedMemory: 10 GiB
    context:
      priority: normal
      preemptible: true
    constraints:
      cluster:
        - ai2/aristo-cirrascale
        - ai2/neptune-cirrascale



# beaker experiment create model_discovery/configs/v_node.yaml 

